package generated;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
* generated by simple-tool in 2017/11/17 02:04:10
**/

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Demo {
    @JsonProperty("ANumberKey")
    private Integer aNumberKey;

    private Float bFloatKey;

    private String cStringKey;

    private Boolean dBoolKey;

    private EObjKey eObjKey;

    private List<Integer> fArrayKey;

    private List<String> gString;

    private List<HArrayObj> hArrayObj;
    
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    @Builder
    public static class EObjKey {
    
        private Integer a;
    }
    
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    @Builder
    public static class HArrayObj {
    
        private Integer a;
    }
}
